### ISSUE TITLE
Problem running js tests from commonTest

### ISSUE THREAD

**Issue by grooverlyTipps** [goncalossilva/kotlinx-resources#46]
First off, this has already saved me a world of trouble, but I'm running into an issue when running the tests as js. It looks like the same issue is actually happening in your builds: 

`> Task :resources-test:jsBrowserTest
"/" is proxied, you should probably change urlRoot to avoid conflicts
Pattern "/Users/runner/work/kotlinx-resources/kotlinx-resources/build/js/packages/resources-resources-test-test/src/jsTest/resources/**" does not match any file.
Pattern "/Users/runner/work/kotlinx-resources/kotlinx-resources/build/js/packages/resources-resources-test-test/src/jsTest/resources/**" does not match any file.`

It looks like there's an issue with running js tests from commonTest.

**Comment by goncalossilva** [comment]
That warning has been there since the very first version of the library. As far as I remember, there isn't any impact in practice. It's just that karma doesn't like when the entire root folder is proxied, which is [exactly what the library does](https://github.com/goncalossilva/kotlinx-resources/blob/ba1ff494e79ceb81105e3e907987abb799f95376/resources-plugin/src/main/kotlin/ResourcesPlugin.kt#L200-L202). It helps ensure the path looks the same as you have locally, when instantiating `Resource`.

Could you please explain what specific problem you are experiencing? What fails (or doesn't fail, but should)?

**Comment by goncalossilva** [comment]
I've mitigated the warning, though it should not have had any practical effect. If you're still experiencing an issue, it may be due to something else.
